[[redirects]]
  from = "/.well_known/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/assetlinks.json"
  status = 200
  force = true

[[redirects]]
    from = "/*"
    to = "https://register.tartanhacks.com"
    status = 301
    force = true
